name: Run API Tests
on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run API Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Setup env
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage
      - name: Run Tests
        run: |
          python -m unittest discover
      - name: Run coverage
        run: |
          coverage --source t2wml -m unittest discover
      - name: Update Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: .coverage




