name: Run API Tests
on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run API Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Setup env
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage
      - name: Run Tests
        run: |
          python -m unittest discover
      - name: Run coverage
        run: |
          coverage run --source t2wml -m unittest discover
      - name: Upload coverall results
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: |
          pip install coveralls
          coveralls




